version: "2"

services:
  web:
    image: reload/drupal-apache-ssl
    ports:
      - '80:80'
      - '443:443'
    volumes:
      # Map webroot
      - './web:/var/www/web'

      - './configuration:/var/www/configuration'
      - './vendor:/var/www/vendor'
      # This is required to make the generated community service client available in
      # the container. composer generates a symlink from /vendor/name/package to
      # the local path. This makes this symlink work on the container as well.
      - './docker/docker.settings.php:/var/www/web/sites/default/settings.php'
      - './docker/docker.settings.local.php:/var/www/web/sites/default/settings.local.php'
      - './docker/docker.services.yml:/var/www/web/sites/default/services.yml:ro'

      - './docker/docker.development.services.yml:/var/www/web/sites/development.services.yml:ro'
      - './docker/etc/cron.conf:/etc/cron.d/cron.conf:ro'
      - './docker/init/prepare-environment.sh:/etc/my_init.d/prepare-environment.sh'
    working_dir: '/var/www/web'
    links:
      - db

  db:
    image: mariadb:10
    ports:
      - '3306:3306'
    volumes:
      - './docker/db/initdb.d:/docker-entrypoint-initdb.d'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db

  drush:
    image: drush/drush:8-php5-alpine
    links:
      - db
    volumes_from:
      - web
    working_dir: /var/www/web
    command: version
