<?php

/**
 * @file
 * Contains forlev_base.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\NodeInterface;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\Plugin\views\query\Sql;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function forlev_base_theme_suggestions_image_alter(array &$suggestions, array $variables, $hook) {
  if (!empty($variables['style_name'])) {
    $suggestions[] = $hook . '__' . $variables['style_name'];
  }
}


/**
 * Implements hook_node_links_alter().
 *
 * Remove read-more links on node-teasers.
 */
function forlev_base_node_links_alter(array &$links, NodeInterface $entity, array &$context) {
  if ('teaser' == $context['view_mode']) {
    unset($links['node']['#links']['node-readmore']);
  }
}

/**
 * Implements hook_form_alter().
 */
function forlev_base_form_alter(&$form, $form_state, $form_id) {
  // Move the see also field into the edit-forms sidebar (aka the
  // "advanced" group).
  // We match node_<nodetype>_edit_form as well as node_<nodetype>_form.
  if (preg_match('#^node_([_a-z]+)(_edit)?_form$#', $form_id)) {

    // Put the sidedeck field in the sidebar.
    if (isset($form['field_see_also'])) {
      $form['see_also_group'] = array(
        '#type' => 'details',
        '#title' => t('See also'),
        '#description' => t(
          'Content that should be displayed at the bottom of the page.'
        ),
        '#group' => 'advanced',
        '#open' => FALSE,
        // Push it all the way to the bottom.
        '#weight' => 1000,
      );

      $form['field_see_also']['#group'] = 'see_also_group';
    }
  }
}


/**
 * Implements hooks_view_query_alter().
 */
function forlev_base_views_query_alter(ViewExecutable $view, Sql $query) {
  if ($view->id() === 'frontpage_content_list') {
    // Sort the list by multiple optional fields.
    $query->addField('node_field_data', 'created');
    $query->addField('node__field_presentation_date', 'field_presentation_date_value', 'field_presentation_date_value');
    $query->addField('node__field_start_date', 'field_start_date_value', 'field_start_date_value');
    $query->addOrderBy(NULL, 'COALESCE(field_presentation_date_value, UNIX_TIMESTAMP(field_start_date_value), created)', 'DESC');
  }
}

