<?php

/**
 * @file
 * Contains forlev_base.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function forlev_base_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the forlev_base module.
    case 'help.page.forlev_base':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Base functionallity') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function forlev_base_theme_suggestions_image_alter(array &$suggestions, array $variables, $hook) {
  if (!empty($variables['style_name'])) {
    $suggestions[] = $hook . '__' . $variables['style_name'];
  }
}
