<?php

/**
 * @file
 * Contains forlev_base.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function forlev_base_theme_suggestions_image_alter(array &$suggestions, array $variables, $hook) {
  if (!empty($variables['style_name'])) {
    $suggestions[] = $hook . '__' . $variables['style_name'];
  }
}


/**
 * Implements hook_node_links_alter().
 *
 * Remove read-more links on node-teasers.
 */
function forlev_base_node_links_alter(array &$links, NodeInterface $entity, array &$context) {
  if ('teaser' == $context['view_mode']) {
    unset($links['node']['#links']['node-readmore']);
  }
}
