determine_menu: true
disable_admin_page: true
append_current_page: false
current_page_as_link: false
hide_on_single_item: true
remove_home: true
home_as_site_name: false
menu_breadcrumb_menus:
  main:
    enabled: '1'
    weight: '-10'
  account:
    weight: '0'
    enabled: 0
  tools:
    weight: '0'
    enabled: 0
  admin:
    weight: '0'
    enabled: 0
  footer:
    weight: '0'
    enabled: 0
_core:
  default_config_hash: rHo9-yiANXMMskoaoz_o6oaG8XoZexWG1HfBc95rdkA
