horizontal_menu: main
horizontal_depth: 2
off_canvas_menus: main
horizontal_wrapping_element: nav
horizontal_breakpoint: desktop
horizontal_media_query: '(min-width: 960px)'
include_css: false
off_canvas_position: right
off_canvas_theme: theme-dark
horizontal_superfish: true
horizontal_superfish_delay: 300
horizontal_superfish_speed: 100
horizontal_superfish_speed_out: 100
horizontal_superfish_hoverintent: true
hammerjs: true
breakpoint_css_filepath: 'public://css'
_core:
  default_config_hash: DgAWl_7_B39CsIvJyK3vxn2mj8fNSQZSQyVRiTlGdrg
