apikey: ''
test_defaults:
  to: mads@danquah.dk
  subject: 'Test Email from SendGrid Module'
  body:
    value: 'Test Message for SendGrid.'
    format: plain_text
  from_name: Mads
  to_name: 'Mads HD'
  reply_to: ''
_core:
  default_config_hash: g4qz7cPnloXFwtnLYfIKI2VS0gf_UFOz_I2uQiiulC8
